[package]
name = "ipass"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
rpassword = "7.2"
rand = "0.8.5"
aes-gcm = "0.10.1"
sha2 = "0.10.6"
hex = "0.4.3"
brotli = "3.3.4"